version: '3.8'

services:
  banco_dados:
    image: postgres:15
    container_name: meu_postgres
    restart: always
    environment:
      POSTGRES_USER: engenheiro
      POSTGRES_PASSWORD: senha_secreta
      POSTGRES_DB: dados_db
    ports:
      - "5432:5432"